#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <assert.h>

#include "darr.h"
#include "sv.h"

#define O_FNAME ".gitignore"
#define CI_COPYRIGHT_SV SV_INIT("# generated by cignore (C) RaysOfBees\n")

#define MAX_CHAR_PER_LINE_SIZE 512

typedef struct {
    sv_t* items;
    size_t count;
    size_t capacity;
} Lines_t;

static Lines_t ls = {0};

typedef enum {
    PSTATE_STDIN,
    PSTATE_FIN,
    PSTATE_COUNT
} Pstate_t;

static Pstate_t gpstate = -1;

bool darr_exists_nonlib(sv_t s, int* idx) {
    for (size_t i = 0; i < ls.count; ++i) {
        if (sv_eq(s, ls.items[i])) {
            *idx = i;
            return true;
        }
    }
    *idx = -1;
    return false;
}

void debug_print_strings_darr() {
    assert(ls.items != NULL);

    printf("--------- DEBUG ---------\n");
    for (int i = ls.count - 1; i >= 0; --i) {
        if (ls.items[i].self[0] == '#') {
            printf(SV_FORMAT"\n", SV_ARGS(ls.items[i]));
            printf("*\n");
        } else {
            printf("!"SV_FORMAT"\n", SV_ARGS(ls.items[i]));
        }  
    }
    printf("------------------------\n");
};

void output_print_strings_darr(FILE* o) {
    assert(ls.items != NULL);

    for (int i = ls.count - 1; i >= 0; --i) {
        if (ls.items[i].self[0] == '#') {
            fprintf(o , SV_FORMAT"\n", SV_ARGS(ls.items[i]));
            fprintf(o, "*\n");
        } else {
            fprintf(o , "!"SV_FORMAT"\n", SV_ARGS(ls.items[i]));
        }
    }
};

void handle_simple_ignore(sv_t sv) {
    darr_append(ls, sv);
};

void handle_complicated_ignore(sv_t* input_sv) {
    sv_t temp_input_copy = sv_copy(input_sv);
    size_t idx = -1;
    bool append_star = false;
    
    if ((temp_input_copy.self[temp_input_copy.length - 1]) == '/'){
        append_star = true;
    }

    while (true) {
        if (sv_is_empty(&temp_input_copy)) {break;}
        if (append_star) {
            sv_trim(&temp_input_copy); // in case of random spaces
            char* temp_input_copy_cstr = malloc(temp_input_copy.length + strlen("*") + 1);
            strcpy(temp_input_copy_cstr, temp_input_copy.self);
            strcat(temp_input_copy_cstr, "*");
            sv_t star_appended_sv = SV_INIT(temp_input_copy_cstr);
            darr_append(ls, star_appended_sv);
            append_star = false;
        } else {
            int exists_idx = -1;
            while (darr_exists_nonlib(temp_input_copy, &exists_idx)) {
                darr_remove_by_index(ls, exists_idx);
            }
            darr_append(ls, temp_input_copy);
        }
        if (!sv_char_exists_with_idx_back(&temp_input_copy, '/', &idx)) {break;}
        sv_cut_by_delim_right(&temp_input_copy, '/');
    }
}

void ci_print_usage() {
    printf("usage (stdin): ci\n");
    printf(".q: quit the program and save to .gitignore (currentlly appends over or creates it)");
    printf("or: ci filename.txt (extention optional)");
};

int main(int argc, char* argv[]) {
    FILE* fip;

    switch (argc) {
        case 1:
            gpstate = PSTATE_STDIN;
            break;
            case 2: {
                printf("opening a file\n");
            gpstate = PSTATE_FIN;
            shift_cargs(argc, argv);
            fip = fopen(*argv, "r");
            if (fip == NULL) {
                printf("failed to open file %s because %s\n", fip, strerror(errno));
                exit(-1);
            }
            break;
        }
        default: {
            printf("too many arguments\n");
            ci_print_usage();
            exit(-1);
        }
    }

    char buf[MAX_CHAR_PER_LINE_SIZE] = {0};

    while (true) {
        if (gpstate == PSTATE_STDIN) {
            printf("enter path: ");
            if (fgets(buf, sizeof(buf), stdin) == NULL) break;
        } else if (gpstate == PSTATE_FIN) {
            if (fgets(buf, sizeof(buf), fip) == NULL) break;
        }

        buf[strcspn(buf, "\n")] = '\0';

        if (strcmp(buf, "q") == 0) {
            darr_append(ls, CI_COPYRIGHT_SV);
            break;
        }

        char* bufdup = strdup(buf);
        sv_t input_sv = SV_INIT(bufdup);

        size_t idx = -1;
        if (!sv_is_empty(&input_sv)){
            if (sv_char_exists_with_idx(&input_sv, '/', &idx)) {
                handle_complicated_ignore(&input_sv);
            } else {
                handle_simple_ignore(input_sv);
            }
        }
    }

    if (gpstate == PSTATE_FIN) {
        darr_append(ls, CI_COPYRIGHT_SV);
        fclose(fip);
    }

    FILE* fp = fopen(O_FNAME, "w");

    if (fp == NULL) {
        printf("could not open file \"%s\" because %s\n", O_FNAME, strerror(errno));
    }

    output_print_strings_darr(fp);

    fclose(fp);
}
